// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhcxzmlfbnemvuowuaml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoY3h6bWxmYm5lbXZ1b3d1YW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjg2NjgsImV4cCI6MjA3MjYwNDY2OH0.Drj4J-vE7vrYiTiTI-LiH2s28SfWszYBDw5WxztYiBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});